import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000';
const req = async (path, options = {}) => {
  const token = localStorage.getItem('token');
  const res = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...options });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.message || 'Something went wrong');
  return data;
};

function Auth({ onLogin }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name:'', email:'', password:'' }); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const submit = async e => { e.preventDefault(); setError(''); setLoading(true); try { const data = await req(`/api/auth/${mode}`, { method:'POST', body:JSON.stringify(form) }); localStorage.setItem('token', data.token); onLogin(data.user); } catch(e){setError(e.message)} finally{setLoading(false)} };
  return <main className="auth"><div className="auth-card"><div className="brand">✓ <span>TaskFlow</span></div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="muted">{mode==='login'?'Stay on top of your work.':'Start organizing your day.'}</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><p className="switch">{mode==='login'?'New here?':'Already have an account?'} <button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create an account':'Sign in'}</button></p></div></main>
}

function App(){
 const [user,setUser]=useState(null),[tasks,setTasks]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState('all'),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[toast,setToast]=useState('');
 useEffect(()=>{const token=localStorage.getItem('token'); if(!token){setLoading(false);return} req('/api/auth/me').then(d=>{setUser(d.user);return req('/api/tasks')}).then(setTasks).catch(()=>localStorage.removeItem('token')).finally(()=>setLoading(false))},[]);
 const refresh=()=>req('/api/tasks').then(setTasks);
 const logout=()=>{localStorage.removeItem('token');setUser(null);setTasks([])};
 const shown=useMemo(()=>tasks.filter(t=>filter==='all'||t.status===filter),[tasks,filter]);
 if(loading)return <div className="loading">Loading TaskFlow…</div>; if(!user)return <Auth onLogin={u=>{setUser(u);refresh()}}/>;
 const stats={all:tasks.length,todo:tasks.filter(t=>t.status==='todo').length,progress:tasks.filter(t=>t.status==='in-progress').length,done:tasks.filter(t=>t.status==='done').length};
 return <div className="app"><header><div className="brand">✓ <span>TaskFlow</span></div><div className="user"><div className="avatar">{user.name[0]}</div><span>{user.name}</span><button className="ghost" onClick={logout}>Log out</button></div></header><section className="hero"><div><p className="eyebrow">PERSONAL WORKSPACE</p><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p className="muted">Plan it. Do it. Done.</p></div><button onClick={()=>{setEditing(null);setModal(true)}}>+ New task</button></section><div className="stats"><Stat n={stats.all} label="All tasks"/><Stat n={stats.todo} label="To do"/><Stat n={stats.progress} label="In progress"/><Stat n={stats.done} label="Completed"/></div><div className="toolbar"><div className="tabs">{[['all','All'],['todo','To do'],['in-progress','In progress'],['done','Completed']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{l}</button>)}</div></div><section className="tasks">{shown.length===0?<div className="empty"><div>✓</div><h2>No tasks here</h2><p>Create a task and get moving.</p></div>:shown.map(t=><TaskCard key={t._id} task={t} onEdit={()=>{setEditing(t);setModal(true)}} onDelete={async()=>{await req(`/api/tasks/${t._id}`,{method:'DELETE'});setTasks(tasks.filter(x=>x._id!==t._id));setToast('Task deleted')}} onStatus={async status=>{const updated=await req(`/api/tasks/${t._id}`,{method:'PATCH',body:JSON.stringify({status})});setTasks(tasks.map(x=>x._id===t._id?updated:x));}}/>)}</section>{modal&&<TaskModal task={editing} close={()=>setModal(false)} save={async payload=>{const data=editing?await req(`/api/tasks/${editing._id}`,{method:'PATCH',body:JSON.stringify(payload)}):await req('/api/tasks',{method:'POST',body:JSON.stringify(payload)});setTasks(editing?tasks.map(x=>x._id===editing._id?data:x):[data,...tasks]);setModal(false);setToast(editing?'Task updated':'Task created')}}/>}{toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}</div>
}
const Stat=({n,label})=><div className="stat"><strong>{n}</strong><span>{label}</span></div>;
function TaskCard({task,onEdit,onDelete,onStatus}){return <article className="task"><button className={`check ${task.status==='done'?'checked':''}`} onClick={()=>onStatus(task.status==='done'?'todo':'done')}>{task.status==='done'?'✓':''}</button><div className="task-main"><div className="task-top"><h3 className={task.status==='done'?'strike':''}>{task.title}</h3><span className={`priority ${task.priority}`}>{task.priority}</span></div>{task.description&&<p>{task.description}</p>}<div className="meta"><span>{task.status.replace('-',' ')}</span>{task.dueDate&&<span>Due {new Date(task.dueDate).toLocaleDateString()}</span>}</div></div><div className="actions"><button onClick={onEdit}>Edit</button><button onClick={onDelete}>Delete</button></div></article>}
function TaskModal({task,close,save}){const [f,setF]=useState(task?{title:task.title,description:task.description,status:task.status,priority:task.priority,dueDate:task.dueDate?task.dueDate.slice(0,10):''}:{title:'',description:'',status:'todo',priority:'medium',dueDate:''}); return <div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();save({...f,dueDate:f.dueDate||null})}}><div className="modal-head"><h2>{task?'Edit task':'New task'}</h2><button type="button" className="close" onClick={close}>×</button></div><label>Title<input autoFocus value={f.title} onChange={e=>setF({...f,title:e.target.value})} required/></label><label>Description<textarea rows="3" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="grid"><label>Priority<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option></select></label><label>Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="todo">To do</option><option value="in-progress">In progress</option><option value="done">Done</option></select></label></div><label>Due date<input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button>{task?'Save changes':'Create task'}</button></div></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
